### ISSUE TITLE
[앱 화면 오류] Qube사전 - 화면 출력 갯수 10개 제한 수정 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/BaseballQube#1]
Qube 사전 조회시 10개로 제한되어 화면에 출력됩니다.

모든 항목 출력 가능하도록 수정 요청드립니다.

(추후에 관리자가 정렬 순서 지정 가능하도록 수정 요청드립니다.)

**Comment by sde-sonjihyun** [comment]
5/26 목록 출력 확인

**Comment by sde-jin** [comment]
처리 완료
