### ISSUE TITLE
[앱 화면 수정] 매치리포트 경기 종료 여부에 "서스펜드" 라디오버튼 추가해주세요

### ISSUE THREAD

**Issue by kyohoonsim** [SportsdataEvolution/BaseballQube#2]
매치리포트 경기 종료 여부에 "서스펜드" 라디오버튼 추가해주세요

![image](https://user-images.githubusercontent.com/58966525/119339312-f8979a00-bccb-11eb-98d3-6462cc7ca42b.png)

**Comment by sde-sonjihyun** [comment]
댓글 테스트

**Comment by sde-jin** [comment]
수정완료

**Comment by kyohoonsim** [comment]
확인했습니다. 감사합니다~!
