### ISSUE TITLE
[기록지 시스템 오류 수정, 개발 요청]

### ISSUE THREAD

**Issue by woodongo** [SportsdataEvolution/BaseballQube#3]
1. '오름차순과 내림차순으로 볼 수 있는 기능 추가 --> 급한건이 절대 아니고 차후에 개발 요청드립니다.

2. 추가 아웃 체크 후 저장 
--> 수정 시 추가 아웃 체크 해제 후 저장하면 체크 해제가 안된 상태로 저장됨
[210524_기록지 시스템 수정 필요사항 정리.xlsx](https://github.com/SportsdataEvolution/BaseballQube/files/6532299/210524_.xlsx)

3. 투구 결과에 야수선택 필요
--> 아웃카운트가 늘어나지 않는 것을 제외하면 모든 점에서
CO와 똑같은 기록 적용.
--> 타자는 1루에 출루하지만 타율은 하락
--> 야수선택 시 주자 아웃일 경우 주자 아웃 체크, 모든 주자 세잎 시 아웃카운트가 올라가지 않으므로 CO와는 다른 야수선택 필요
--> 야수선택은 (Fielder`s choice) FC로 표기 

엑셀 파일 참조하였습니다.

**Comment by kyohoonsim** [comment]
@woodongo 우대리님 제목에서 대략적으로 어떤 문제인지 알 수 있게 해주시면 감사하겠습니다 ㅎㅎ 그리고 이슈를 작은 단위로 하나하나 분리해서 올려주시는 것이 좋아요 ㅎㅎ
