### ISSUE TITLE
[앱 화면 오류] 스탯큐브 - 키움 히어로즈 로고 변경 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/BaseballQube#4]
스탯큐브 - 키움 히어로즈 로고 오타 있어 수정 요청드립니다.
![키움 히어로즈 로고 오타](https://user-images.githubusercontent.com/82424617/119424335-36cea100-bd40-11eb-923b-7333522fa3a1.jpg)

**Comment by sde-jin** [comment]
수정완료
