### ISSUE TITLE
[앱 화면 오류] 스탯큐브 - 볼 하나 빠진 코스 판정 스트라이크 항목 제외

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/BaseballQube#6]
스탯큐브 - 타자 - 핫콜드존 하단 표 '볼 하나 빠진 코스 판정 스트라이크' 항목 제외 요청드립니다.

※ 기존 '볼 하나 빠진 코스 판정 스트라이크' 는 투수 분석 항목인데 현재 타자 분석 항목에 포함되어있음

**Comment by sde-jin** [comment]
수정완료

**Comment by kyohoonsim** [comment]
확인했습니다~감사합니다!
